[View in Colaboratory](https://colab.research.google.com/github/tjwei/NDHU_AM1130/blob/master/2018_Week06_numpy.ipynb)

In [0]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [5]:
a[0]

1

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[3]=777777
a

array([     1,      2,      3, 777777])

In [9]:
123**123

114374367934617190099880295228066276746218078451850229775887975052369504785666896446606568365201542169649974727730628842345343196581134895919942820874449837212099476648958359023796078549041949007807220625356526926729664064846685758382803707100766740220839267

In [12]:
len(str((123**123)**123))

31619

In [16]:
1+1

2

In [17]:
2**64

18446744073709551616

In [19]:
2**128

340282366920938463463374607431768211456

In [20]:
a

array([     1,      2,      3, 777777])

In [21]:
a.dtype

dtype('int64')

In [23]:
a[3] = 123**123

OverflowError: ignored

In [0]:
a[3] = 2**63-1

In [28]:
a

array([                  1,                   2,                   3,
       9223372036854775807])

In [32]:
a[2] = -2**63
a

array([                   1,                    2, -9223372036854775808,
        9223372036854775807])

In [33]:
["aaa", 0, 0.3, {"dog":"dog"} ]

['aaa', 0, 0.3, {'dog': 'dog'}]

In [35]:
a.append

AttributeError: ignored

In [36]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [37]:
np.array([1,2,3]) + np.array([4,5,6])

array([5, 7, 9])

In [0]:
u = np.array([1,2,3])
v = np.array([4,5,6])

In [40]:
u+v

array([5, 7, 9])

In [41]:
u-v

array([-3, -3, -3])

In [42]:
u*v

array([ 4, 10, 18])

In [43]:
sum(u*v)

32

In [44]:
(u*v).sum()

32

In [45]:
u @ v

32

In [46]:
u.dot(v)

32

In [47]:
np.dot(u, v)

32

$ u \cdot v$


$ < u, v >$

In [48]:
np.sin(u)

array([0.84147098, 0.90929743, 0.14112001])

In [52]:
np.sin(np.deg2rad(np.array(range(0, 91,5))))

array([0.        , 0.08715574, 0.17364818, 0.25881905, 0.34202014,
       0.42261826, 0.5       , 0.57357644, 0.64278761, 0.70710678,
       0.76604444, 0.81915204, 0.8660254 , 0.90630779, 0.93969262,
       0.96592583, 0.98480775, 0.9961947 , 1.        ])

In [0]:
import matplotlib.pyplot as plt