[View in Colaboratory](https://colab.research.google.com/github/tjwei/NDHU_AM1130/blob/master/2018_Week06_numpy.ipynb)

In [0]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [5]:
a[0]

1

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[3]=777777
a

array([     1,      2,      3, 777777])