[View in Colaboratory](https://colab.research.google.com/github/tjwei/NDHU_AM1130/blob/master/2018_Week06_numpy.ipynb)

In [0]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [5]:
a[0]

1

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[3]=777777
a

array([     1,      2,      3, 777777])

In [9]:
123**123

114374367934617190099880295228066276746218078451850229775887975052369504785666896446606568365201542169649974727730628842345343196581134895919942820874449837212099476648958359023796078549041949007807220625356526926729664064846685758382803707100766740220839267

In [12]:
len(str((123**123)**123))

31619

In [16]:
1+1

2

In [17]:
2**64

18446744073709551616

In [19]:
2**128

340282366920938463463374607431768211456

In [20]:
a

array([     1,      2,      3, 777777])

In [21]:
a.dtype

dtype('int64')

In [23]:
a[3] = 123**123

OverflowError: ignored

In [0]:
a[3] = 2**63-1

In [28]:
a

array([                  1,                   2,                   3,
       9223372036854775807])

In [32]:
a[2] = -2**63
a

array([                   1,                    2, -9223372036854775808,
        9223372036854775807])

In [33]:
["aaa", 0, 0.3, {"dog":"dog"} ]

['aaa', 0, 0.3, {'dog': 'dog'}]

In [35]:
a.append

AttributeError: ignored